### ISSUE TITLE
Failed to merge segment - cannot fit 'int' into an index-sized integer

### ISSUE THREAD

**Issue by The-KLF** [firedm/FireDM#428] opened 2022-01-31 20:24 UTC
Just tried FireDM for windows, version 2021-12-26 and trying to download a zip file.  FireDM is configured to use up to 8 connections per download.  So far, I have been unable to download a zip file successfully.  The logs are flooded with errors trying to merge the segments together.  Some log entries have the "cannot fit 'int' into an index-sized integer.  Others simply have no other info.

Pausing and resuming the download does not resolve the issue.
I am not sure if previous versions worked as this is the first time I am trying the application. 
--Edit--
I also tested version 2021.9.5 and reproduced the issue - will continue to try older versions
I tested 2021.6.18 and reproduced the issue

Sample of log output:

>> failed to merge segment D:\firedm_uid_0d581c944ae4a2a873192e032fe4b1bf\0  -  
>> failed to merge segment D:\firedm_uid_0d581c944ae4a2a873192e032fe4b1bf\7  -  
>> failed to merge segment D:\firedm_uid_0d581c944ae4a2a873192e032fe4b1bf\8  -  
>> failed to merge segment D:\firedm_uid_0d581c944ae4a2a873192e032fe4b1bf\6  -  
>> failed to merge segment D:\firedm_uid_0d581c944ae4a2a873192e032fe4b1bf\5  -  
>> failed to merge segment D:\firedm_uid_0d581c944ae4a2a873192e032fe4b1bf\1  -  
>> failed to merge segment D:\firedm_uid_0d581c944ae4a2a873192e032fe4b1bf\11  -  
>> failed to merge segment D:\firedm_uid_0d581c944ae4a2a873192e032fe4b1bf\10  -  
>> failed to merge segment D:\firedm_uid_0d581c944ae4a2a873192e032fe4b1bf\12  -  
>> failed to merge segment D:\firedm_uid_0d581c944ae4a2a873192e032fe4b1bf\9  -  
>> failed to merge segment D:\firedm_uid_0d581c944ae4a2a873192e032fe4b1bf\16  -  
>> failed to merge segment D:\firedm_uid_0d581c944ae4a2a873192e032fe4b1bf\15  -  
>> failed to merge segment D:\firedm_uid_0d581c944ae4a2a873192e032fe4b1bf\2  -  
>> failed to merge segment D:\firedm_uid_0d581c944ae4a2a873192e032fe4b1bf\20  -  
>> failed to merge segment D:\firedm_uid_0d581c944ae4a2a873192e032fe4b1bf\19  -  
>> failed to merge segment D:\firedm_uid_0d581c944ae4a2a873192e032fe4b1bf\21  -  
>> failed to merge segment D:\firedm_uid_0d581c944ae4a2a873192e032fe4b1bf\18  -  
>> failed to merge segment D:\firedm_uid_0d581c944ae4a2a873192e032fe4b1bf\25  -  
>> failed to merge segment D:\firedm_uid_0d581c944ae4a2a873192e032fe4b1bf\24  -  
>> failed to merge segment D:\firedm_uid_0d581c944ae4a2a873192e032fe4b1bf\3  -  cannot fit 'int' into an index-sized integer
>> failed to merge segment D:\firedm_uid_0d581c944ae4a2a873192e032fe4b1bf\36  -  
>> failed to merge segment D:\firedm_uid_0d581c944ae4a2a873192e032fe4b1bf\35  -  
>> failed to merge segment D:\firedm_uid_0d581c944ae4a2a873192e032fe4b1bf\34  -  
>> failed to merge segment D:\firedm_uid_0d581c944ae4a2a873192e032fe4b1bf\38  -  
>> failed to merge segment D:\firedm_uid_0d581c944ae4a2a873192e032fe4b1bf\33  -  
>> failed to merge segment D:\firedm_uid_0d581c944ae4a2a873192e032fe4b1bf\41  -  
>> failed to merge segment D:\firedm_uid_0d581c944ae4a2a873192e032fe4b1bf\32  -  
>> failed to merge segment D:\firedm_uid_0d581c944ae4a2a873192e032fe4b1bf\49  -  
>> failed to merge segment D:\firedm_uid_0d581c944ae4a2a873192e032fe4b1bf\48  -  
>> failed to merge segment D:\firedm_uid_0d581c944ae4a2a873192e032fe4b1bf\47  -  
>> failed to merge segment D:\firedm_uid_0d581c944ae4a2a873192e032fe4b1bf\58  -  
>> failed to merge segment D:\firedm_uid_0d581c944ae4a2a873192e032fe4b1bf\60  -  
>> failed to merge segment D:\firedm_uid_0d581c944ae4a2a873192e032fe4b1bf\57  -  
>> failed to merge segment D:\firedm_uid_0d581c944ae4a2a873192e032fe4b1bf\4  -  cannot fit 'int' into an index-sized integer

**Comment by firedm** [comment] 2022-01-31 22:10
@The-KLF 
please post a link/url for this file or any other file to reproduce the same issue

**Comment by The-KLF** [comment] 2022-02-01 01:22
After more testing, I believe the issue is able to be reproduced more often when you have segments that are larger than 1GB.  However what I cannot explain is that sometimes it retries successfully.  What I did below was set the connections to 3, and so it downloaded 3 segments that were at 1.21 GB.  It immediately got errors when trying to combine the segments.  It ddn't throw the 'int' error though.  I will keep testing


=============================================================================
>> start downloading file: "debian-11.2.0-amd64-DVD-1.iso", size: 3.63 GB, to: D:\
>> url: "https://cdimage.debian.org/debian-cd/current/amd64/iso-dvd/debian-11.2.0-amd64-DVD-1.iso" 

>> Thread Manager()> concurrency method: Individual Threads
>> Seg 0 start, size: 1.21 GB - range: [0, 1299212969]  - worker 2
>> Seg 1 start, size: 1.21 GB - range: [1299212970, 2598425939]- minimum speed= 20480, timeout=10  - worker 0
>> Seg 2 start, size: 1.21 GB - range: [2598425940, 3897638911]- minimum speed= 20480, timeout=10  - worker 1
>> downloaded segment:  0 [0, 1299212969] 1.21 GB - worker 2
>> Seg 3 start, size: 148.3 MB - range: [3742140371, 3897638911]- minimum speed= 20480, timeout=10  - worker 2
>> downloaded segment:  3 [3742140371, 3897638911] 148.3 MB - worker 2
>> Seg 4 start, size: 26.8 MB - range: [2570371400, 2598425939]- minimum speed= 20480, timeout=10  - worker 2
>> downloaded segment:  1 [1299212970, 2570371399] 1.18 GB - worker 0
>> downloaded segment:  4 [2570371400, 2598425939] 26.8 MB - worker 2
>> Seg 5 start, size: 10.8 MB - range: [3730811101, 3742140370]- minimum speed= 20480, timeout=10  - worker 0
>> Seg 6 start, size: 5.4 MB - range: [3736475737, 3742140370]- minimum speed= 20480, timeout=10  - worker 2
>> downloaded segment:  6 [3736475737, 3742140370] 5.4 MB - worker 2
>> downloaded segment:  2 [2598425940, 3730811100] 1.05 GB - worker 1
>> Seg 7 start, size: 2.7 MB - range: [3733643420, 3736475736]- minimum speed= 20480, timeout=10  - worker 1
>> completed segment:  0
**>> failed to merge segment D:\firedm_uid_b8b1b83ee5e5278beeed3256f3398ba1\1  -**  
**>> failed to merge segment D:\firedm_uid_b8b1b83ee5e5278beeed3256f3398ba1\2  -**  
>> Seg 8 start, size: 1.4 MB - range: [3732227261, 3733643419]- minimum speed= 20480, timeout=10  - worker 2
>> downloaded segment:  8 [3732227261, 3733643419] 1.4 MB - worker 2
>> downloaded segment:  7 [3733643420, 3736475736] 2.7 MB - worker 1
>> Seg 5 start, size: 1.4 MB - range: [3730811101, 3732227260]- minimum speed= 20480, timeout=10  - worker 1
>> downloaded segment:  5 [3730811101, 3732227260] 1.4 MB - worker 1
>> thread_manager uid_b8b1b83ee5e5278beeed3256f3398ba1: quitting
>> completed segment:  3
>> completed segment:  1
>> completed segment:  4
>> completed segment:  2
>> completed segment:  5
>> completed segment:  8
>> completed segment:  7
>> completed segment:  6

done renaming file: D:\firedm_uid_b8b1b83ee5e5278beeed3256f3398ba1\_temp_debian-11.2.0-amd64-DVD-1.iso ... to: D:\debian-11.2.0-amd64-DVD-1.iso

**Comment by The-KLF** [comment] 2022-02-01 01:40
Hi realized I was still testing the older version, but I found another link that reliably fails.  This test is on the latest 2021.12.26 windows version:

>> --------------------------------------------------
>> start downloading file: "10GB.bin", size: 9.77 GB, to: D:\
>> url: "https://speed.hetzner.de/10GB.bin" 

>> failed to merge segment D:\firedm_uid_9ce4a94b2ffd4f89f63602f68c711a20\1  -  
>> failed to merge segment D:\firedm_uid_9ce4a94b2ffd4f89f63602f68c711a20\1  -  
>> failed to merge segment D:\firedm_uid_9ce4a94b2ffd4f89f63602f68c711a20\1  -  
>> failed to merge segment D:\firedm_uid_9ce4a94b2ffd4f89f63602f68c711a20\1  -  
>> failed to merge segment D:\firedm_uid_9ce4a94b2ffd4f89f63602f68c711a20\1  -  
>> failed to merge segment D:\firedm_uid_9ce4a94b2ffd4f89f63602f68c711a20\1  -  
>> failed to merge segment D:\firedm_uid_9ce4a94b2ffd4f89f63602f68c711a20\1  -  
>> failed to merge segment D:\firedm_uid_9ce4a94b2ffd4f89f63602f68c711a20\1  -  
>> failed to merge segment D:\firedm_uid_9ce4a94b2ffd4f89f63602f68c711a20\1  -  
>> failed to merge segment D:\firedm_uid_9ce4a94b2ffd4f89f63602f68c711a20\1  -  
>> failed to merge segment D:\firedm_uid_9ce4a94b2ffd4f89f63602f68c711a20\1  -  
>> merge max errors exceeded for: D:\firedm_uid_9ce4a94b2ffd4f89f63602f68c711a20\1 
>> auto refresh url for: 10GB.bin
>> get_headers()> (7, 'Failed to connect to speed.hetzner.de port 443: Network unreachable')
>> 

>> --------------------------------------------------
>> start downloading file: "10GB.bin", size: 9.77 GB, to: D:\
>> url: "https://speed.hetzner.de/10GB.bin" 

>> load_progress_info()> rebuild segments from previous download for: 10GB.bin
>> failed to merge segment D:\firedm_uid_9ce4a94b2ffd4f89f63602f68c711a20\1  -  
>> failed to merge segment D:\firedm_uid_9ce4a94b2ffd4f89f63602f68c711a20\1  -  
>> failed to merge segment D:\firedm_uid_9ce4a94b2ffd4f89f63602f68c711a20\1  -  
>> failed to merge segment D:\firedm_uid_9ce4a94b2ffd4f89f63602f68c711a20\1  -  
>> failed to merge segment D:\firedm_uid_9ce4a94b2ffd4f89f63602f68c711a20\1  -  
>> failed to merge segment D:\firedm_uid_9ce4a94b2ffd4f89f63602f68c711a20\1  -  
>> failed to merge segment D:\firedm_uid_9ce4a94b2ffd4f89f63602f68c711a20\1  -  
>> failed to merge segment D:\firedm_uid_9ce4a94b2ffd4f89f63602f68c711a20\1  -  
>> failed to merge segment D:\firedm_uid_9ce4a94b2ffd4f89f63602f68c711a20\1  -  
>> failed to merge segment D:\firedm_uid_9ce4a94b2ffd4f89f63602f68c711a20\1  -  
>> failed to merge segment D:\firedm_uid_9ce4a94b2ffd4f89f63602f68c711a20\1  -  
>> merge max errors exceeded for: D:\firedm_uid_9ce4a94b2ffd4f89f63602f68c711a20\1 
>> controller: too many connection errors maybe network problem or expired link

**Comment by firedm** [comment] 2022-02-01 14:17
> After more testing, I believe the issue is able to be reproduced more often when you have segments that are larger than 1GB. However what I cannot explain is that sometimes it retries successfully. What I did below was set the connections to 3, and so it downloaded 3 segments that were at 1.21 GB. It immediately got errors when trying to combine the segments. It ddn't throw the 'int' error though. I will keep testing

@The-KLF 
thanks for your positive investigation, will try to reproduce the issue and see what we can do to fix it

**Comment by firedm** [comment] 2022-02-06 18:15
@The-KLF 
please check if this problem is fixed in the new version 2021-2-5

**Comment by The-KLF** [comment] 2022-02-06 20:19
Hi @firedm
Good news, I am testing it now and so far it looks like the issue is fixed!

I do see that downloads use double the space until completed.  Is that by design or a bug?

**Comment by firedm** [comment] 2022-02-07 02:06
@The-KLF 

> Good news, I am testing it now and so far it looks like the issue is fixed!

Great!

> I do see that downloads use double the space until completed. Is that by design or a bug?

this by design, segments will be downloaded separately, then merged into one file, after this segments will be removed, 
this way if download gets interrupted by any reason, it can be resumed again safely

but when downloading big files this technique should be enhanced to save disk space, 
will consider this enhancement in future releases of FireDM

**Closed by firedm** 2022-02-07 02:06 UTC
