### ISSUE TITLE
New download stops at 99%

### ISSUE THREAD

**Issue by trimechee** [firedm/FireDM#372] opened 2021-11-20 20:48 UTC
Hello, I can download facebook video without worry but sometimes even with the new version of FireDM,  the facebook watch video download freezes at 99%, I tried to stop and restart the download of this video, delete and download it again, restart FireDM. .... but it does not work: here is the link of the video:

https://www.facebook.com/100053886966000/videos/810508629735468

and this is the log : 

>> -------------------- FireDM --------------------
>> Starting FireDM version: 2021.11.18 Frozen
>> operating system: Os: Windows - Platform: Windows-10-10.0.19041 - Machine: AMD64
>> Python version: 3.8.3 (tags/v3.8.3:6f8c832, May 13 2020, 22:20:19) [MSC v.1925 32 bit (Intel)]
>> current working directory: C:\FireDM_2021.11.18\FireDM
>> FFMPEG: C:\FireDM_2021.11.18\FireDM\ffmpeg.exe, version: n4.4.1-3-gbf862ee122-20211116
>> Tkinter version: 8.6.9
>> AwesomeTkinter version: 2021.11.8
>> Pillow version: 8.2.0
>> PyCUrl version: PycURL/7.43.0.5 libcurl/7.68.0 OpenSSL/1.1.1d zlib/1.2.11 c-ares/1.15.0 WinIDN libssh2/1.9.0 nghttp2/1.40.0
>> 
>> controller.get_d_list()> sending d_list
>> url watchdog active!
>> systray disabled in settings ...
>> yt_dlp version: 2021.11.10.1, load_time= 1 seconds
>> youtube_dl version: 2021.06.06, load_time= 2 seconds
>> Gui Loading time: 2.92 seconds 
>> set default extractor engine to: yt_dlp <module 'yt_dlp' from 'C:\\FireDM_2021.11.18\\FireDM\\lib\\yt_dlp\\__init__.py'>
>> creating video playlist
>> [generic] permalink: Requesting header
>> [generic] Falling back on generic information extractor.
>> [generic] permalink: Downloading webpage
>> [generic] permalink: Extracting information
>> no video streams detected
>> creating video playlist
>> [generic] 9p5AJ6Ksvz: Requesting header
>> [redirect] Following redirect to https://www.facebook.com/100053886966000/videos/810508629735468/
>> [facebook] 810508629735468: Downloading webpage
>> [facebook] unable to extract OpenGraph title; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
>> downloading Thumbnail
>> controller> playlist ready
>> check ffmpeg availability?
>> ffmpeg checked ok! - at: C:\FireDM_2021.11.18\FireDM\ffmpeg.exe, version: n4.4.1-3-gbf862ee122-20211116
>> download item uid_3926d9389d4afc6224c221fc98f80149 already in list, check resume availability
>> resume is possible
>> downloads items list saved in: C:\FireDM_2021.11.18\FireDM\downloads.dat
>> 

>> --------------------------------------------------
>> start downloading file: "المعز الحاج منصور_
رسالة الى رئيس... - المعز الحاج منصور.m4a", size: 7.6 MB, to: D:\Downloads
>> url: "https://www.facebook.com/100053886966000/videos/810508629735468/" 

>> Seg 0 start, size: 7.6 MB - range: [0, 7968006]- minimum speed= 20480, timeout=10  - worker 2
>> Seg 1 start, size: 3.8 MB - range: [3984004, 7968006]- minimum speed= 20480, timeout=10  - worker 0
>> Seg 2 start, size: 1.84 MB - range: [2058284, 3984003]- minimum speed= 20480, timeout=10  - worker 1
>> check ffmpeg availability?
>> ffmpeg checked ok! - at: C:\FireDM_2021.11.18\FireDM\ffmpeg.exe, version: n4.4.1-3-gbf862ee122-20211116
>> download item uid_3926d9389d4afc6224c221fc98f80149 already in list, check resume availability
>> download is already in progress for this item
>> downloaded segment:  0 [0, 2058283] 1.96 MB - worker 2
>> Seg 3 start, size: 1.21 MB - range: [6696302, 7968006]- minimum speed= 20480, timeout=10  - worker 2
>> downloaded segment:  3 [6696302, 7968006] 1.21 MB - worker 2
>> downloaded segment:  2 [2058284, 3984003] 1.84 MB - worker 1
>> downloaded segment:  1 [3984004, 6696301] 2.59 MB - worker 0
>> thread_manager uid_3926d9389d4afc6224c221fc98f80149: quitting

**Comment by firedm** [comment] 2021-11-20 23:42
@trimechee 

just tried to download the same video and i couldn't reproduce the same error, it completed successfully

however i see in the above log that segment number zero has wrong range
will do some more investigation

**Comment by trimechee** [comment] 2021-11-21 17:16
Thank you :) I specify that this bug occurs with audio streams, that is to say I download the audio streams of the faceboon videos, I choose the m4a format, I just chose the aac audio foramt and it's the same problem ....

I specify that I was using 3D Youtube Downloader to directly download the audio streams of facebook videos, it works but the size of the audio stream was large and greater than the size of the same audio downloaded by FireDM ..... that's what prompted me to migrate to FireDM where I could often download the audio stream from facebook videos with small size .... so i think if 3D Youtube Downloader doesn't download lower quality audio streams from facebook videos it is to avoid this bug maybe ....

I just tried ti donwload video ant same bug : 

>> -------------------- FireDM --------------------
>> Starting FireDM version: 2021.11.18 Frozen
>> operating system: Os: Windows - Platform: Windows-10-10.0.19041 - Machine: AMD64
>> Python version: 3.8.3 (tags/v3.8.3:6f8c832, May 13 2020, 22:20:19) [MSC v.1925 32 bit (Intel)]
>> current working directory: C:\FireDM_2021.11.18\FireDM
>> FFMPEG: C:\FireDM_2021.11.18\FireDM\ffmpeg.exe, version: n4.4.1-3-gbf862ee122-20211116
>> Tkinter version: 8.6.9
>> AwesomeTkinter version: 2021.11.8
>> Pillow version: 8.2.0
>> PyCUrl version: PycURL/7.43.0.5 libcurl/7.68.0 OpenSSL/1.1.1d zlib/1.2.11 c-ares/1.15.0 WinIDN libssh2/1.9.0 nghttp2/1.40.0
>> 
>> controller.get_d_list()> sending d_list
>> url watchdog active!
>> systray disabled in settings ...
>> yt_dlp version: 2021.11.10.1, load_time= 7 seconds
>> Gui Loading time: 10.04 seconds 
>> set default extractor engine to: yt_dlp <module 'yt_dlp' from 'C:\\FireDM_2021.11.18\\FireDM\\lib\\yt_dlp\\__init__.py'>
>> youtube_dl version: 2021.06.06, load_time= 16 seconds
>> creating video playlist
>> [facebook] 810508629735468: Downloading webpage
>> [facebook] unable to extract OpenGraph title; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
>> downloading Thumbnail
>> controller> playlist ready
>> check ffmpeg availability?
>> ffmpeg checked ok! - at: C:\FireDM_2021.11.18\FireDM\ffmpeg.exe, version: n4.4.1-3-gbf862ee122-20211116
>> download item uid_3926d9389d4afc6224c221fc98f80149 already in list, check resume availability
>> resume is possible
>> downloads items list saved in: C:\FireDM_2021.11.18\FireDM\downloads.dat
>> 

>> --------------------------------------------------
>> start downloading file: "المعز الحاج منصور_
رسالة الى رئيس... - المعز الحاج منصور.m4a", size: 7.6 MB, to: D:\Downloads
>> url: "https://www.facebook.com/watch/live/?ref=watch_permalink&v=810508629735468" 

>> load_progress_info()> rebuild segments from previous download for: المعز الحاج منصور_
رسالة الى رئيس... - المعز الحاج منصور.m4a
>> thread_manager uid_3926d9389d4afc6224c221fc98f80149: quitting
>> check ffmpeg availability?
>> ffmpeg checked ok! - at: C:\FireDM_2021.11.18\FireDM\ffmpeg.exe, version: n4.4.1-3-gbf862ee122-20211116
>> download item uid_3926d9389d4afc6224c221fc98f80149 already in list, check resume availability
>> download is already in progress for this item
>> check ffmpeg availability?
>> ffmpeg checked ok! - at: C:\FireDM_2021.11.18\FireDM\ffmpeg.exe, version: n4.4.1-3-gbf862ee122-20211116
>> download item uid_3926d9389d4afc6224c221fc98f80149 already in list, check resume availability
>> download is already in progress for this item
>> check ffmpeg availability?
>> ffmpeg checked ok! - at: C:\FireDM_2021.11.18\FireDM\ffmpeg.exe, version: n4.4.1-3-gbf862ee122-20211116
>> download item uid_3926d9389d4afc6224c221fc98f80149 already in list, check resume availability
>> download is already in progress for this item
>> check ffmpeg availability?
>> ffmpeg checked ok! - at: C:\FireDM_2021.11.18\FireDM\ffmpeg.exe, version: n4.4.1-3-gbf862ee122-20211116
>> downloads items list saved in: C:\FireDM_2021.11.18\FireDM\downloads.dat
>> check ffmpeg availability?
>> ffmpeg checked ok! - at: C:\FireDM_2021.11.18\FireDM\ffmpeg.exe, version: n4.4.1-3-gbf862ee122-20211116
>> download item uid_f38b233ab07763fa80aa1b75237155fb already in list, check resume availability
>> resume is possible
>> downloads items list saved in: C:\FireDM_2021.11.18\FireDM\downloads.dat
>> File Paused.
>> brain uid_3926d9389d4afc6224c221fc98f80149: quitting
>> -------------------------------------------------- 

>> check ffmpeg availability?
>> ffmpeg checked ok! - at: C:\FireDM_2021.11.18\FireDM\ffmpeg.exe, version: n4.4.1-3-gbf862ee122-20211116
>> download item uid_f38b233ab07763fa80aa1b75237155fb already in list, check resume availability
>> resume is possible
>> downloads items list saved in: C:\FireDM_2021.11.18\FireDM\downloads.dat
>> 

>> --------------------------------------------------
>> start downloading file: "المعز الحاج منصور_
رسالة الى رئيس... - المعز الحاج منصور.aac", size: 7.6 MB, to: D:\Downloads
>> url: "https://www.facebook.com/watch/live/?ref=watch_permalink&v=810508629735468" 

>> Seg 0 start, size: 7.6 MB - range: [0, 7968006]- minimum speed= 20480, timeout=10  - worker 2
>> Seg 1 start, size: 3.8 MB - range: [3984004, 7968006]- minimum speed= 20480, timeout=10  - worker 1
>> Seg 2 start, size: 1.85 MB - range: [2041155, 3984003]- minimum speed= 20480, timeout=10  - worker 0
>> downloaded segment:  0 [0, 2041154] 1.95 MB - worker 2
>> Seg 3 start, size: 1.42 MB - range: [6483310, 7968006]- minimum speed= 20480, timeout=10  - worker 2
>> downloaded segment:  2 [2041155, 3984003] 1.85 MB - worker 0
>> downloaded segment:  3 [6483310, 7968006] 1.42 MB - worker 2
>> downloaded segment:  1 [3984004, 6483309] 2.38 MB - worker 1
>> thread_manager uid_f38b233ab07763fa80aa1b75237155fb: quitting
>> File Paused.
>> brain uid_f38b233ab07763fa80aa1b75237155fb: quitting
>> -------------------------------------------------- 

>> check ffmpeg availability?
>> ffmpeg checked ok! - at: C:\FireDM_2021.11.18\FireDM\ffmpeg.exe, version: n4.4.1-3-gbf862ee122-20211116
>> downloads items list saved in: C:\FireDM_2021.11.18\FireDM\downloads.dat
>> 

>> --------------------------------------------------
>> start downloading file: "المعز الحاج منصور_
رسالة الى رئيس... - المعز الحاج منصور.mp4", size: 21.8 MB, to: D:\Downloads
>> url: "https://www.facebook.com/watch/live/?ref=watch_permalink&v=810508629735468" 

>> Seg 0 start, size: 14.2 MB - range: [0, 14886215]- minimum speed= 20480, timeout=10  - worker 2
>> Seg 0_audio start, size: 7.6 MB - range: [0, 7968006]- minimum speed= 20480, timeout=10  - worker 0
>> Seg 2 start, size: 7.07 MB - range: [7468430, 14886215]- minimum speed= 20480, timeout=10  - worker 1
>> downloaded segment:  0 [0, 7468429] 7.12 MB - worker 2
>> Seg 3 start, size: 1.49 MB - range: [6409582, 7968006]- minimum speed= 20480, timeout=10  - worker 2
>> downloaded segment:  2 [7468430, 14886215] 7.07 MB - worker 1
>> downloaded segment:  3 [6409582, 7968006] 1.49 MB - worker 2
>> downloaded segment:  0_audio [0, 6409581] 6.11 MB - worker 0
>> thread_manager uid_7a51e12628c0dd58d76e7ea24caa76b4: quitting

**Comment by trimechee** [comment] 2021-11-21 17:22
I specify that FireDM is installed in C: protected and the download folder is located in a folder in D:

**Comment by firedm** [comment] 2021-11-21 18:25
ok, will do more tests to check what is the problem

**Comment by trimechee** [comment] 2021-11-22 17:20
Thank you :)

**Comment by firedm** [comment] 2021-12-04 14:43
@trimechee 
is this problem fixed in new version or it still happens?

**Comment by trimechee** [comment] 2021-12-04 15:55
I downloaded a lot of facebook videos and their audio stream using the latest version of FireDM and also with the previous version of FireDM and have not encountered any problems! but i will try to re-download this meme video which i failed to upload in the past and i will see the result in sha Allah

**Comment by trimechee** [comment] 2021-12-04 16:02
I download this problematic facebook video to extract the audio stream and it works !!
Thank you vey much dor the fix :) 

here the log : 

>> -------------------- FireDM --------------------
>> Starting FireDM version: 2021.12.2 Frozen
>> operating system: Os: Windows - Platform: Windows-10-10.0.19041 - Machine: AMD64
>> Python version: 3.8.3 (tags/v3.8.3:6f8c832, May 13 2020, 22:20:19) [MSC v.1925 32 bit (Intel)]
>> current working directory: C:\FireDM_2021.12.2\FireDM
>> FFMPEG: C:\FireDM_2021.12.2\FireDM\ffmpeg.exe, version: n4.4.1-3-gbf862ee122-20211116
>> Tkinter version: 8.6.9
>> AwesomeTkinter version: 2021.11.8
>> Pillow version: 8.2.0
>> PyCUrl version: PycURL/7.43.0.5 libcurl/7.68.0 OpenSSL/1.1.1d zlib/1.2.11 c-ares/1.15.0 WinIDN libssh2/1.9.0 nghttp2/1.40.0
>> 
>> controller.get_d_list()> sending d_list
>> url watchdog active!
>> systray disabled in settings ...
>> Gui Loading time: 9.89 seconds 
>> [facebook] 810508629735468: Downloading webpage
>> [facebook] unable to extract OpenGraph title; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
>> controller> playlist ready
>> 

>> --------------------------------------------------
>> start downloading file: "المعز الحاج منصور - رسالة الى رئيس... - المعز الحاج منصور.opus", size: 7.6 MB, to: D:\Downloads
>> url: "https://www.facebook.com/watch/live/?ref=watch_permalink&v=810508629735468" 

>> handling audio streams
>> [opus @ 04cb7c80] Unsupported codec id in stream 0
>> Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
>> Error initializing output stream 0:0 --
>> 
>> size=       0kB time=00:00:00.01 bitrate= 169.5kbits/s speed=N/A
>> size=      69kB time=00:00:09.57 bitrate=  58.8kbits/s speed=19.1x
>> size=     256kB time=00:00:32.13 bitrate=  65.3kbits/s speed=32.1x
>> size=     256kB time=00:00:54.49 bitrate=  38.5kbits/s speed=36.3x
>> size=     512kB time=00:01:16.93 bitrate=  54.5kbits/s speed=38.4x
>> size=     768kB time=00:01:39.67 bitrate=  63.1kbits/s speed=39.8x
>> size=    1024kB time=00:02:02.11 bitrate=  68.7kbits/s speed=40.7x
>> size=    1280kB time=00:02:24.31 bitrate=  72.7kbits/s speed=41.2x
>> size=    1536kB time=00:02:46.75 bitrate=  75.5kbits/s speed=41.6x
>> size=    1536kB time=00:03:09.11 bitrate=  66.5kbits/s speed=  42x
>> size=    1792kB time=00:03:31.11 bitrate=  69.5kbits/s speed=42.2x
>> size=    2048kB time=00:03:53.17 bitrate=  72.0kbits/s speed=42.4x
>> size=    2304kB time=00:04:15.33 bitrate=  73.9kbits/s speed=42.5x
>> size=    2560kB time=00:04:37.37 bitrate=  75.6kbits/s speed=42.6x
>> size=    2816kB time=00:04:59.69 bitrate=  77.0kbits/s speed=42.8x
>> size=    3072kB time=00:05:21.89 bitrate=  78.2kbits/s speed=42.9x
>> size=    3072kB time=00:05:43.77 bitrate=  73.2kbits/s speed=42.9x
>> size=    3328kB time=00:06:05.45 bitrate=  74.6kbits/s speed=  43x
>> size=    3584kB time=00:06:27.71 bitrate=  75.7kbits/s speed=  43x
>> size=    3840kB time=00:06:49.51 bitrate=  76.8kbits/s speed=43.1x
>> size=    4096kB time=00:07:11.61 bitrate=  77.7kbits/s speed=43.1x
>> size=    4352kB time=00:07:33.59 bitrate=  78.6kbits/s speed=43.2x
>> size=    4608kB time=00:07:55.61 bitrate=  79.4kbits/s speed=43.2x
>> size=    4608kB time=00:08:17.11 bitrate=  75.9kbits/s speed=43.2x
>> size=    4864kB time=00:08:38.83 bitrate=  76.8kbits/s speed=43.2x
>> size=    5120kB time=00:08:59.35 bitrate=  77.8kbits/s speed=43.1x
>> size=    5376kB time=00:09:21.29 bitrate=  78.5kbits/s speed=43.1x
>> size=    5632kB time=00:09:43.25 bitrate=  79.1kbits/s speed=43.2x
>> size=    5888kB time=00:10:04.21 bitrate=  79.8kbits/s speed=43.1x
>> size=    5888kB time=00:10:26.35 bitrate=  77.0kbits/s speed=43.2x
>> size=    6144kB time=00:10:46.31 bitrate=  77.9kbits/s speed=  43x
>> size=    6400kB time=00:11:05.85 bitrate=  78.7kbits/s speed=42.9x
>> size=    6656kB time=00:11:27.49 bitrate=  79.3kbits/s speed=42.9x
>> size=    6656kB time=00:11:47.81 bitrate=  77.0kbits/s speed=42.9x
>> size=    6912kB time=00:12:09.99 bitrate=  77.6kbits/s speed=42.9x
>> size=    7168kB time=00:12:32.17 bitrate=  78.1kbits/s speed=42.9x
>> size=    7424kB time=00:12:54.53 bitrate=  78.5kbits/s speed=  43x
>> size=    7680kB time=00:13:16.51 bitrate=  79.0kbits/s speed=  43x
>> size=    7936kB time=00:13:38.43 bitrate=  79.4kbits/s speed=  43x
>> size=    7936kB time=00:14:00.37 bitrate=  77.4kbits/s speed=43.1x
>> size=    8192kB time=00:14:22.21 bitrate=  77.8kbits/s speed=43.1x
>> size=    8448kB time=00:14:44.31 bitrate=  78.3kbits/s speed=43.1x
>> size=    8704kB time=00:15:06.59 bitrate=  78.6kbits/s speed=43.1x
>> size=    8960kB time=00:15:28.47 bitrate=  79.1kbits/s speed=43.1x
>> size=    9216kB time=00:15:50.61 bitrate=  79.4kbits/s speed=43.2x
>> size=    9472kB time=00:16:12.55 bitrate=  79.8kbits/s speed=43.2x
>> size=    9544kB time=00:16:17.61 bitrate=  80.0kbits/s speed=43.2x
>> File: المعز الحاج منصور - رسالة الى رئيس... - المعز الحاج منصور.opus, saved at: D:\Downloads

**Comment by firedm** [comment] 2021-12-04 16:53
Great

**Closed by firedm** 2021-12-04 16:53 UTC
