### ISSUE TITLE
Google drive support.

### ISSUE THREAD

**Issue by hongyi-zhao** [firedm/FireDM#226] opened 2021-03-11 03:28 UTC
I forget whether this issue has been discussed, if so, I am very sorry. It seems that firedm can't download file from Google Drive, say [this](https://drive.google.com/u/0/uc?id=18eeA54RApJf8Zt0M5oeNeXvX1VTQt7KC&export=download). Any hints for this feature?

Regards,
HY

**Comment by firedm** [comment] 2021-03-12 11:21
@hongyi-zhao 
there is an official way to download thru google drive API, but this is not the right way to implement this feature
still looking for a solid way to get a direct download link for big files

**Comment by hongyi-zhao** [comment] 2021-03-12 14:27
> but this is not the right way to implement this feature

Why?

**Comment by firedm** [comment] 2021-03-15 08:44
closing as duplicate of issue # 144

**Closed by firedm** 2021-03-15 08:44 UTC
