### ISSUE TITLE
The minimum segment size and its influence on downloading performance: trade-offs based on segment size and segment number.

### ISSUE THREAD

**Issue by hongyi-zhao** [firedm/FireDM#223] opened 2021-02-18 03:15 UTC
When I download a huge file, such as [Ubuntu install image](https://releases.ubuntu.com/20.04.2.0/ubuntu-20.04.2.0-desktop-amd64.iso), I noticed that the segment size will gradually become smaller and smaller as the download proceeds, from `27.4 MB` to `119 KB`. The problem is, as the download nears its end, too many small size segments can seriously degrade download performance. So, I think that some trade-offs based on segment size and segment number should be added to the dynamic segmentation algorithm.

Regards,
HY

**Comment by firedm** [comment] 2021-02-18 08:01
@hongyi-zhao 
Agree, the too many chunks at the end will degrade speed, will find a way to fix this

**Comment by firedm** [comment] 2021-02-20 11:41
Fixed,
chunk size will be calculated dynamically based on current download speed, plus some fixes in automatic segmentation logic.

@hongyi-zhao 
please check if problem solved

**Comment by hongyi-zhao** [comment] 2021-02-20 13:02
It delivers a good performance, but I observed a new problem:  the file information of the already downloaded part cannot be updated in realtime on the `Downloads` panel.

**Comment by firedm** [comment] 2021-02-20 14:30
> But I observed a new problem: the file information of the already downloaded part cannot be updated in real-time on the `Downloads` panel for most of the time before the entire download process is complete, instead, the download information will be updated when the entire file is close to or has been downloaded successfully.

This is weird, i can't reproduce this problem, there was an error and already fixed
can you make sure you are running on latest commit

**Comment by hongyi-zhao** [comment] 2021-02-21 00:32
See the following for the commit hash of `FireDM`:
```
$ git log -1
commit f7166798a6cccdbdb577549b4950495779a71670 (HEAD -> master, origin/master, origin/HEAD)
Author: firedm <mahmoud.aboghazala@gmail.com>
Date:   Sat Feb 20 17:24:40 2021 +0200

    [gui] prevent window resize to zero
```

See the following screenshot for the info shown on `Downloads` panel:

![image](https://user-images.githubusercontent.com/11155854/108611938-ae79f080-741e-11eb-9edd-1bc6b091822d.png)

It's obviously that the following equation does not hold:

`47% = 363.0 MB of 2068 GB`

**Comment by firedm** [comment] 2021-02-21 09:29
I tried to download same file and get real time update with right percentage 
see below screenshot
![image](https://user-images.githubusercontent.com/58998813/108620700-9ada8400-7436-11eb-8960-091df7f39162.png)

I think it might be your high download speed with a lot of workers
Can you test with one connection only, and if problem solved repeat the test using 8 connections
from Settings>Network>connections per download

if above didn't solve the problem try speed limit to 2MB just for testing

**Comment by hongyi-zhao** [comment] 2021-02-21 10:05
Thanks for your analysis. It seems the problem only will be clearly observed for connections number >=  15. I'm not sure if it can be fixed.

HY

**Comment by hongyi-zhao** [comment] 2021-02-21 10:05
Thanks for your analysis. It seems the problem only will be clearly observed for connections number >=  15. I'm not sure if it can be fixed.

HY

**Comment by firedm** [comment] 2021-02-21 10:08
> Thanks for your analysis. It seems the problem only will be clearly observed for connections number >= 15. I'm not sure if it can be fixed.
> 
> HY

This great!, knowing the problem is 90% of the solution
i will look for a fix for this

**Comment by hongyi-zhao** [comment] 2021-02-21 12:55
Another thing to be noted: the downloading performance is not always proportional to the total number of connections. In detail, a parabola with the bottom on top can approximate the dependence between them. That said, in any specific network environment, there is an optimal number of connections, which is neither the largest nor the smallest, for a particular download task.

**Comment by firedm** [comment] 2021-02-23 10:24
@hongyi-zhao 
please test latest updates and see if gui real-time update has been fixed with too many connections

**Comment by hongyi-zhao** [comment] 2021-02-23 14:06
Wonderful. I tried to use a high number of connections ranging from 30 to 100 for several times and haven't observe this problem. So, I conclude that it should have been fixed. See the screenshot shown below for detailed info:  

![image](https://user-images.githubusercontent.com/11155854/108854036-5dd2e500-7622-11eb-8314-4a01af661aec.png)

 As you can see, the burstable internet speed of FireDM has reached or exceeded the up limit bandwidth promised by the ISP which is 500Mbps for my current ordered package.

**Comment by firedm** [comment] 2021-02-23 18:16
This is great news :), i am so happy it works as expected.

Good job for your active contribution :+1:

**Closed by firedm** 2021-02-23 18:16 UTC
Labels: Done, Enhancement
