### ISSUE TITLE
CMD blinking on screen while retrieving information from the given link

### ISSUE THREAD

**Issue by nero-0** [firedm/FireDM#344] opened 2021-11-08 20:13 UTC
After providing some link to FireDM and it starts checking the available streams to download, the cmd.exe will blink twice:
![preview](https://user-images.githubusercontent.com/42862510/140808826-30b71a78-282a-4b43-a20c-a5478507f8db.gif)
This started with the latest version, so I don't think it is the expected behavior... besides being a bit annoying. :disappointed_relieved:

I'm on windows, if that matters.

**Comment by firedm** [comment] 2021-11-08 21:22
@nero
thanks for reporting this
this is true, it is not an expected behavior, will investigate why this is happening

**Comment by firedm** [comment] 2021-11-09 20:14
@nero-0 
the cause of this is yt-dlp, will investigate further for a fix
for a temporary workaround, you can change to youtube-dl  from Settings>Video Options>select video extractor engine

**Comment by nero** [comment] 2021-11-10 23:14
This is slightly offtopic, despite both of us having previously contributed to void linux, @nero (me) and @nero-0 are distinct persons. I guess its a mishap writing the mention.

**Comment by firedm** [comment] 2021-11-11 03:43
> This is slightly offtopic, despite both of us having previously contributed to void linux, @nero (me) and @nero-0 are distinct persons. I guess its a mishap writing the mention.

@nero  sorry for this, its a typo

**Comment by firedm** [comment] 2021-11-11 03:46
@nero-0  
@smaragdus
bug has been fixed in yt-dlp version 2021.11.10.1, you can update thru FireDM Update button

**Comment by nero-0** [comment] 2021-11-13 22:20
Solved. Thanks!

**Closed** 2021-11-13 22:20 UTC
Labels: bug
