### ISSUE TITLE
failed to merge segment - [Errno 2] No such file or directory  (infinite loop)

### ISSUE THREAD

**Issue by jdaniele71** [firedm/FireDM#315] opened 2021-10-30 01:31 UTC
Hi,

it is not the first time i see this error on the logs.

https://user-images.githubusercontent.com/69006279/139513435-16e06c83-345b-4dcd-a35e-e30fea1bd818.mp4

It seems there is an infinite loop that produces tons of repeating lines of errors.
The unique lines are actually only five:

>> failed to merge segment V:\Capture\AudioVideo\FireDM\firedm_uid_879258a4d160849c872aa825e33a4725\2  -  [Errno 2] No such file or directory: 'V:\\Capture\\AudioVideo\\FireDM\\firedm_uid_879258a4d160849c872aa825e33a4725\\2'
>> failed to merge segment V:\Capture\AudioVideo\FireDM\firedm_uid_879258a4d160849c872aa825e33a4725\3  -  [Errno 2] No such file or directory: 'V:\\Capture\\AudioVideo\\FireDM\\firedm_uid_879258a4d160849c872aa825e33a4725\\3'
>> failed to merge segment V:\Capture\AudioVideo\FireDM\firedm_uid_879258a4d160849c872aa825e33a4725\4  -  [Errno 2] No such file or directory: 'V:\\Capture\\AudioVideo\\FireDM\\firedm_uid_879258a4d160849c872aa825e33a4725\\4'
>> failed to merge segment V:\Capture\AudioVideo\FireDM\firedm_uid_d847cac1c90f01a94dd52ca834265c07\4  -  [Errno 2] No such file or directory: 'V:\\Capture\\AudioVideo\\FireDM\\firedm_uid_d847cac1c90f01a94dd52ca834265c07\\4'
>> failed to merge segment V:\Capture\AudioVideo\FireDM\firedm_uid_2cda16c477c289ab49f97c63983d5dff\4  -  [Errno 2] No such file or directory: 'V:\\Capture\\AudioVideo\\FireDM\\firedm_uid_2cda16c477c289ab49f97c63983d5dff\\4'

Thanks
Daniele

**Comment by firedm** [comment] 2021-10-30 18:27
this sometimes happens on windows due to operating system buffering, where the file still in system memory and not yet written to harddisk, that's why firedm can't find it
to minimize this error flooding the log (looks glitches, but it is not), we'll add a delay time after each error to give os a time to flush its buffer and write the files to disk, with 30 errors or more it will mark download as failed

**Comment by jdaniele71** [comment] 2021-10-30 22:38
> this sometimes happens on windows due to operating system buffering, where the file still in system memory and not yet written to harddisk, that's why firedm can't find it to minimize this error flooding the log (looks glitches, but it is not), we'll add a delay time after each error to give os a time to flush its buffer and write the files to disk, with 30 errors or more it will mark download as failed

I know it is not a glitch of the log text box because i cleared the log in the video, and it started to write errors again.
By the way, I'm not sure a delay it will solve the issue.
The errors were there since minutes, repeating forever.
I can understand the OS could delay the writing for about 1-2 seconds but not forever.
How can you explain that?

Usually there are flush() methods on classes related to files.
If not present, the code could close the file (so forcing to write to disk) and reopen it.
I don't know if the library that has to write on disk already does that... 🙄

Thanks
Daniele

**Comment by firedm** [comment] 2021-10-31 01:03
> I can understand the OS could delay the writing for about 1-2 seconds but not forever.
How can you explain that?

this might not the actual reason for this, i'm just guessing, since i couldn't reproduce the same error on my machine
hope you find the root cause for this, and we can then fix it

> the code could close the file (so forcing to write to disk) and reopen it.

yes, this is what the code currently does,  [code reference link](https://github.com/firedm/FireDM/blob/75f15af71ad28cc80c824c386610a2cc53ac1a1a/firedm/brain.py#L154)

**Comment by jdaniele71** [comment] 2021-11-05 02:02
When this error happens, downloads are actually frozen even if they reports a positive speed:

![image](https://user-images.githubusercontent.com/69006279/140445574-d088bea3-cfae-463b-80a5-1374fb879863.png)

![image](https://user-images.githubusercontent.com/69006279/140445696-25b17115-e540-4ba3-8d0c-e57970733113.png)

**Comment by firedm** [comment] 2021-11-05 02:39
what happens if you keep it like this for a couple of seconds, does it mark itself as failed?
what happen when you pause then start download again?

**Comment by jdaniele71** [comment] 2021-11-05 22:53
> what happens if you keep it like this for a couple of seconds, does it mark itself as failed? 

A couple of seconds? I left them there for minutes. Log errors keep going on...forever.

> what happen when you pause then start download again?

Sometimes they re-start from scratch, sometimes they just complete what missing.

I had many videos freezing at 99%....probably because at 99% everything has been downloaded but the process fails to merge the segments.

It would be interesting to run the app in VS Code, while debugging (maybe you can give me some hint because i had no time to do that up to now), but I will.

Thanks
Daniele

**Comment by firedm** [comment] 2021-11-18 15:44
@jdaniele71 
please check if problem fixed in new version

**Comment by jdaniele71** [comment] 2021-11-19 01:24
> @jdaniele71 please check if problem fixed in new version

OK, I will in the weekend. I'm very busy in this period, sorry.

**Closed** 2022-01-06 13:18 UTC
