### ISSUE TITLE
Some testings on the performance and hehaviours of git master FireDM.

### ISSUE THREAD

**Issue by hongyi-zhao** [firedm/FireDM#217] opened 2021-02-10 08:08 UTC
In Ubuntu 20.04, I try to download the [proxmox VE 6.3 ISO installer](https://www.proxmox.com/en/downloads?task=callelement&format=raw&item_id=551&element=f85c494b-2b32-4109-b8c1-083cca2b7db6&method=download&args[0]=99f2d3a74bcf6a35ade543cc9b457207) with git master version of FireDM. But I found that the resume operation will cause the file to be downloaded from the beginning.

Any hints for this problem will highly be appreciated. OTOH, the observed downloading speed fluctuates within a large range.

Regards,
HY

**Comment by firedm** [comment] 2021-02-10 08:48
@hongyi-zhao 
when tested the above link found that server doesn't support chunk downloads, so if download stop it can't be resumed and must be started from the beginning
if you set log level to 3 in FireDM> Log, and refresh the link you will see the response headers from the server don't include "accept-ranges" entry, 

`>> headers: {'date': 'wed, 10 feb 2021 08:43:12 gmt', 'content-type': 'application/x-cd-image', 'content-length': '852299776', 'set-cookie': '2f4d6fdc46bcd694b9e7af987293628a=u462k63cglt0mkimm2jg2sef7d; path=/; secure; httponly', 'pragma': 'public', 'cache-control': 'must-revalidate, post-check=0, pre-check=0', 'expires': '0', 'content-transfer-encoding': 'binary', 'content-disposition': 'attachment; filename="proxmox-ve_6.3-1.iso"; modification-date="wed, 25 nov 2020 16:51:19 +0100"; size=852299776;', 'strict-transport-security': 'max-age=63072000', 'x-content-type-options': 'nosniff', 'status_code': 200, 'eff_url': 'https://www.proxmox.com/en/downloads?task=callelement&format=raw&item_id=551&element=f85c494b-2b32-4109-b8c1-083cca2b7db6&method=download&args%5B0%5D=99f2d3a74bcf6a35ade543cc9b457207'}


for more info see https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Ranges 

for fluctuating speed, i will do more tests 
also found a bug in filename resolving need to be fixed

**Comment by firedm** [comment] 2021-02-10 11:58
I believe speed fluctuation might caused by error in auto-file-segmentation and now it should be steady after the fix

Also added a warning popup when downloading a non-resumable files

![image](https://user-images.githubusercontent.com/58998813/107507184-e031c280-6ba7-11eb-936b-e5fdf20583f5.png)

**Comment by hongyi-zhao** [comment] 2021-02-10 13:14
I tried these commits and find that it will give a very slow downloading speed as shown below:

![image](https://user-images.githubusercontent.com/11155854/107514259-65d36380-6be4-11eb-9c16-dd5c1d324ea4.png)

But with curl I can obtain very high downloading speed as following with the same socks5 proxy:

```
$ curl -x socks5://127.0.0.1:18888 'https://www.proxmox.com/en/downloads?task=callelement&format=raw&item_id=551&element=f85c494b-2b32-4109-b8c1-083cca2b7db6&method=download&args[0]=99f2d3a74bcf6a35ade543cc9b457207' -o /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  2  812M    2 19.0M    0     0  2777k      0  0:04:59  0:00:07  0:04:52 3557k^C
```
OTOH, I can't delete these items from the download panel at all with all right key menu entries tried.

**Comment by firedm** [comment] 2021-02-10 15:14
> But with curl I can obtain a very high downloading speed as following with the same socks5 proxy:

i suspect you might accidentally set "speed limit field"
better if you share a screenshot of  Settings>Network

Also can you start FireDM and copy the lines on the log to show some info like mine below:

```
>> -------------------- FireDM --------------------
>> Starting FireDM version: 2021.2.9 Non-Frozen
>> operating system: Linux-5.10.11-zen2-1-zen-x86_64-with-glibc2.32 - x86_64
>> Python version: 3.9.1 (default, Dec 13 2020, 11:55:53) 
[GCC 10.2.0]
>> FFMPEG: /usr/bin/ffmpeg
>> Tkinter version: 8.6.11
>> AwesomeTkinter version: 2021.1.7
>> Pillow version: 8.1.0
>> PyCUrl version: PycURL/7.43.0.6 libcurl/7.74.0 OpenSSL/1.1.1i zlib/1.2.11 zstd/1.4.8 libidn2/2.3.0 libpsl/0.21.1 (+libidn2/2.3.0) libssh2/1.9.0 nghttp2/1.41.0
```

**Comment by hongyi-zhao** [comment] 2021-02-10 15:52
```
>> -------------------- FireDM --------------------
>> Starting FireDM version: 2021.2.9 Non-Frozen
>> operating system: Linux-5.4.0-42-generic-x86_64-with-glibc2.31 - x86_64
>> Python version: 3.9.1 (default, Feb 10 2021, 15:30:33) 
[GCC 9.3.0]
>> current working directory: /home/werner/Public/repo/github.com/firedm/FireDM.git/firedm
>> FFMPEG: /usr/local/bin/ffmpeg
>> Tkinter version: 8.6.10
>> AwesomeTkinter version: 2021.1.7
>> Pillow version: 8.1.0
>> PyCUrl version: PycURL/7.43.0.6 libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3
>> 
>> controller.get_d_list()> sending d_list
>> url watchdog active!
>> systray disabled in settings ...

```

**Comment by firedm** [comment] 2021-02-10 15:56
> OTOH, I can't delete these items from the Downloads panel at all with all right key menu entries tried.

you can delete items by checking them and press "delete" button or click on red small trash can button near each item
also from right click menu "Clear all items" to delete all

don't forget to write the word "delete" in popup menu and press "ok"

![image](https://user-images.githubusercontent.com/58998813/107534483-973e3600-6bc8-11eb-8a81-2b9c2289ad6d.png)

**Comment by firedm** [comment] 2021-02-10 16:26
> ```
> >> -------------------- FireDM --------------------
> >> Starting FireDM version: 2021.2.9 Non-Frozen
> >> operating system: Linux-5.4.0-42-generic-x86_64-with-glibc2.31 - x86_64
> >> Python version: 3.9.1 (default, Feb 10 2021, 15:30:33) 
> [GCC 9.3.0]
> >> current working directory: /home/werner/Public/repo/github.com/firedm/FireDM.git/firedm
> >> FFMPEG: /usr/local/bin/ffmpeg
> >> Tkinter version: 8.6.10
> >> AwesomeTkinter version: 2021.1.7
> >> Pillow version: 8.1.0
> >> PyCUrl version: PycURL/7.43.0.6 libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3
> >> 
> >> controller.get_d_list()> sending d_list
> >> url watchdog active!
> >> systray disabled in settings ...
> ```

your system seems up to date, I have no clue why you have this slow speed

one last thing we can try
please download this AppImage file, make it executable and run it to see if you still have this slow speed
it has mostly everything packed

https://github.com/firedm/FireDM/releases/download/2021.2.9/FireDM-2021.2.9-x86_64.AppImage

**Comment by hongyi-zhao** [comment] 2021-02-11 00:21
It still shows lower efficiency than curl:

![image](https://user-images.githubusercontent.com/11155854/107589737-9dbcc400-6c41-11eb-9491-bcddee09cdaf.png)
  
OTOH, when I copy the download URL shown on its [website](https://www.proxmox.com/en/downloads/item/proxmox-ve-6-3-iso-installer), FireDM will automatically capture the link and assign an error file name as shown above.

**Comment by firedm** [comment] 2021-02-11 06:29
> I retested the downloading job reported here with both git master FireDM and the AppImage, now it seems that both are great now as far as downloading speed is concerned, as shown below:

This is great!

> But when I copy the download URL shown on its website, Appimage version of FireDM will automatically capture the link and assign an error file name as shown above while the git master version doesn't have this problem.

filename extraction already fixed in git version and it will be available in coming AppImage release

**Closed** 2021-03-18 15:58 UTC
